from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .generator import DEFAULT_PATTERNS, detect_sage_package, generate
from .installer import install_stub_package, uninstall_stub_package
from .preparser import preparse_path
from .translate import USER_CACHE_DIR


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Batch-generate PyCharm-friendly .pyi files from an installed SageMath "
            "package. Run with Sage's Python interpreter."
        )
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(sys.prefix) / "sage_typings",
        help="Build directory for generated stubs (default: <current environment>/sage_typings)",
    )
    parser.add_argument(
        "--source",
        type=Path,
        help="Optional path to the installed sage package; normally auto-detected",
    )
    parser.add_argument(
        "--pattern",
        action="append",
        dest="patterns",
        help='Relative glob to include; repeatable (default: "**/*.pyx")',
    )
    parser.add_argument(
        "--exclude",
        action="append",
        default=[],
        help="Relative glob to exclude; repeatable",
    )
    parser.add_argument(
        "--include-py",
        action="store_true",
        help=(
            "Also stub pure-Python modules (*.py) — not just the compiled "
            "Cython modules (*.pyx).  Package inits, tests, dynamic "
            "distribution shims and the all.py re-export files are skipped "
            "automatically; --exclude adds more.  The .pyi keeps every "
            "public def/class (bodies stripped to the docstring) so PyCharm "
            "can type element chains through pure-Python functions "
            "(e.g. prime_divisors in sage/arith/misc.py)."
        ),
    )
    parser.add_argument(
        "--include-private",
        action="store_true",
        help="Include private Cython functions in generated stubs",
    )
    parser.add_argument(
        "--no-all-stub",
        action="store_true",
        help="Do not generate explicit exports for sage.all",
    )
    parser.add_argument(
        "--no-runtime-docs",
        action="store_true",
        help=(
            "Skip runtime docstring collection (importing every Sage module "
            "takes minutes); keep source-extracted and curated docs only"
        ),
    )
    parser.add_argument(
        "--doc-language",
        choices=["zh", "en"],
        default="zh",
        help=(
            "Docstring language: 'zh' applies the curated Chinese docs "
            "(default); 'en' keeps the original English docstrings while "
            "still applying the language-neutral type annotations"
        ),
    )
    parser.add_argument(
        "--install",
        action="store_true",
        help=(
            "Install generated .pyi files beside the current Sage runtime modules; "
            "recommended for PyCharm WSL interpreters (strict checks are automatic)"
        ),
    )
    parser.add_argument(
        "--overwrite-unowned",
        action="store_true",
        help=(
            "With --install: take over pre-existing .pyi files that this tool does "
            "not own on the same paths, backing each up to <name>.pyi.sps-bak "
            "(restored by --uninstall). Use to replace stale third-party stubs"
        ),
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove only .pyi files previously installed into Sage by this tool",
    )
    parser.add_argument(
        "--strict-factories",
        action="store_true",
        help="Fail instead of installing when a detected dynamic factory is unresolved",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help=(
            "Refuse installation if a module fails, a dynamic factory is unresolved, "
            "or a public sage.all export falls back to Any"
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help=(
            "With --install: overwrite stubs that were generated by a NEWER "
            "version of this tool (which would lose their documentation "
            "enrichment) instead of refusing"
        ),
    )
    parser.add_argument("--verbose", action="store_true")

    subparsers = parser.add_subparsers(dest="command")
    preparse_parser = subparsers.add_parser(
        "preparse",
        help=(
            "Rewrite Sage preparser syntax (R.<x> = GF(2)[], ^, e^(-1)) in "
            ".py files into plain Python so static analysis can parse them"
        ),
    )
    preparse_parser.add_argument("files", nargs="+", type=Path)
    preparse_parser.add_argument(
        "--output",
        type=Path,
        help="Write converted copies into this directory instead of rewriting in place",
    )
    preparse_parser.add_argument(
        "--check",
        action="store_true",
        help="Only report files that need conversion; exit 1 if any do",
    )
    preparse_parser.add_argument(
        "--no-backup",
        action="store_true",
        help="Do not keep a .preparse-backup copy of rewritten files",
    )
    preparse_parser.add_argument(
        "--force",
        action="store_true",
        help="Convert again even when the file carries the conversion marker",
    )
    preparse_parser.add_argument(
        "--json",
        action="store_true",
        help="Print one JSON object per file on stdout (stable for IDE use)",
    )
    conformance_parser = subparsers.add_parser(
        "conformance",
        help=(
            "Cross-check the curated return-type fixes against the "
            "annotations declared in the installed Sage sources: reports "
            "matches, conflicts (data layer disagrees with upstream) and "
            "unannotated targets (the curated fix is still needed)"
        ),
    )
    conformance_parser.add_argument(
        "--source",
        type=Path,
        help="Installed Sage package root (default: auto-detected)",
    )
    conformance_parser.add_argument(
        "--json",
        action="store_true",
        help="Print one JSON object per finding (stable for automation)",
    )
    conformance_parser.add_argument(
        "--runtime",
        action="store_true",
        help=(
            "Additionally execute the doctest examples of every curated "
            "return entry against the live Sage runtime and verify that the "
            "runtime type fits the declared annotation (reports base-class "
            "declarations hiding concrete subclasses)"
        ),
    )
    translate_parser = subparsers.add_parser(
        "translate-docs",
        help=(
            "OPT-IN: machine-translate the remaining English stub docstrings "
            "into Chinese and store them in a persistent cache.  Never runs "
            "automatically during --install, so English-only users are "
            "unaffected unless they invoke this command explicitly."
        ),
    )
    translate_parser.add_argument(
        "--stubs",
        type=Path,
        help="Stub tree to translate (default: the installed Sage package)",
    )
    translate_parser.add_argument(
        "--cache",
        type=Path,
        default=USER_CACHE_DIR / "translations.json",
        help="Translation cache file (default: ~/.sage-pycharm-stubgen/translations.json)",
    )
    translate_parser.add_argument(
        "--bundled",
        type=Path,
        help=(
            "Lower-priority bundled cache to merge first.  Defaults to the "
            "translations.json shipped inside the package when present."
        ),
    )
    translate_parser.add_argument(
        "--no-bundled",
        action="store_true",
        help="Do not merge the cache shipped inside the package",
    )
    translate_parser.add_argument(
        "--limit",
        type=int,
        help="Only translate the first N untranslated docstrings (for testing)",
    )
    translate_parser.add_argument(
        "--backend",
        choices=["google", "baidu"],
        default="google",
        help=(
            "Translation backend: 'google' (free endpoint, batched, may be "
            "rate-limited) or 'baidu' (LLM text translation API; needs "
            "BAIDU_APPID plus BAIDU_API_KEY or BAIDU_SECRET env vars)"
        ),
    )
    translate_parser.add_argument(
        "--workers",
        type=int,
        default=4,
        help="Parallel translation workers for the baidu backend (default: 4)",
    )
    translate_parser.add_argument(
        "--apply-only",
        action="store_true",
        help="Skip translating; only apply existing cache entries to the stubs",
    )
    return parser


def run_preparse(args: argparse.Namespace) -> int:
    import json
    from dataclasses import asdict

    exit_code = 0
    results = []
    for path in args.files:
        result = preparse_path(
            path,
            check_only=args.check,
            backup=not args.no_backup,
            output_dir=args.output,
            force=args.force,
        )
        results.append(result)
        if result.error:
            exit_code = 2
        elif result.changed and args.check:
            exit_code = 1

    if args.json:
        print(
            json.dumps(
                [
                    {**asdict(item), "path": str(item.path), "backup": str(item.backup) if item.backup else None}
                    for item in results
                ],
                ensure_ascii=False,
            )
        )
        return exit_code

    for result in results:
        if result.error:
            print(f"Failed: {result.path}: {result.error}", file=sys.stderr)
        elif result.changed:
            if args.check:
                print(f"Needs preparse: {result.path}")
            else:
                message = f"Preparsed: {result.path}"
                if result.backup is not None:
                    message += f" (backup: {result.backup})"
                print(message)
        else:
            print(f"Clean: {result.path}")
    return exit_code


def run_conformance_cmd(args: argparse.Namespace) -> int:
    from .conformance import (
        count_source_annotations,
        run_conformance,
        run_runtime_checks,
    )

    source_root = args.source
    if source_root is None:
        source_root, _ = detect_sage_package()

    findings = run_conformance(source_root)
    counts = {"unannotated": 0, "ok": 0, "conflict": 0}
    for finding in findings:
        counts[finding.status] += 1

    runtime_findings = run_runtime_checks(source_root) if args.runtime else []
    runtime_counts = {"ok": 0, "mismatch": 0, "skipped": 0}
    for finding in runtime_findings:
        runtime_counts[finding.status] += 1

    if args.json:
        import json as _json

        for finding in findings:
            print(_json.dumps(finding.as_json(), ensure_ascii=False))
        for finding in runtime_findings:
            print(_json.dumps(finding.as_json(), ensure_ascii=False))
        return 0

    print(f"Sage source root: {source_root}")
    print(f"Annotated callables in the shipped sources: {count_source_annotations(source_root)}")
    print(
        f"Curated return fixes checked: {len(findings)} "
        f"(ok {counts['ok']}, unannotated {counts['unannotated']}, conflict {counts['conflict']})"
    )
    for finding in findings:
        if finding.status == "conflict":
            print(
                f"CONFLICT {finding.module}.{finding.qualname}: "
                f"curated={finding.curated!r} source={finding.annotation!r}"
            )
    if args.runtime:
        print(
            f"Runtime probes: {len(runtime_findings)} "
            f"(ok {runtime_counts['ok']}, mismatch {runtime_counts['mismatch']}, "
            f"skipped {runtime_counts['skipped']})"
        )
        for finding in runtime_findings:
            if finding.status == "mismatch":
                print(
                    f"MISMATCH {finding.module}.{finding.qualname}: "
                    f"declared={finding.declared!r} runtime={finding.actual!r} ({finding.detail})"
                )
    return 0


def run_translate_docs(args: argparse.Namespace) -> int:
    from .translate import (
        TranslationCache,
        apply_translations,
        iter_english_docstrings,
        translate_texts,
    )

    stubs_root = args.stubs
    if stubs_root is None:
        stubs_root, _ = detect_sage_package()

    cache = TranslationCache(args.cache)
    bundled = args.bundled
    if bundled is None and not args.no_bundled:
        shipped = Path(__file__).resolve().parent / "translations.json"
        if shipped.is_file():
            bundled = shipped
    if bundled is not None:
        cache.merge(bundled)

    if not args.apply_only:
        pending = [
            (stub, doc)
            for stub, doc in iter_english_docstrings(stubs_root)
            if doc not in cache.data
        ]
        if args.limit is not None:
            pending = pending[: args.limit]
        total = len(pending)
        done = 0
        import os

        backend_kwargs = {}
        if args.backend == "baidu":
            appid = os.environ.get("BAIDU_APPID")
            api_key = os.environ.get("BAIDU_API_KEY")
            secret = os.environ.get("BAIDU_SECRET")
            if not appid or not (api_key or secret):
                print(
                    "The baidu backend needs BAIDU_APPID plus either "
                    "BAIDU_API_KEY (Bearer auth) or BAIDU_SECRET (sign auth) "
                    "environment variables.",
                    file=sys.stderr,
                )
                return 2
            backend_kwargs = {
                "appid": appid,
                "api_key": api_key,
                "secret": secret,
            }
        # Translate and persist in chunks so an interrupted run resumes from
        # the cache instead of restarting from zero.
        for start in range(0, total, 200):
            chunk = pending[start : start + 200]
            translated, failed = translate_texts(
                [doc for _, doc in chunk],
                backend=args.backend,
                workers=args.workers,
                **backend_kwargs,
            )
            cache.data.update(translated)
            cache.save()
            done += len(translated)
            print(f"Progress: {done}/{total} translated, {failed} failed", flush=True)

    applied = apply_translations(stubs_root, cache.data)
    print(f"Applied: {applied}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.command == "preparse":
        return run_preparse(args)
    if args.command == "conformance":
        return run_conformance_cmd(args)
    if args.command == "translate-docs":
        return run_translate_docs(args)
    if args.install and args.uninstall:
        parser.error("--install and --uninstall cannot be used together")

    if args.uninstall:
        sage_package, sage_version = detect_sage_package()
        result = uninstall_stub_package(sage_package)
        print(f"SageMath: {sage_version}")
        print(f"Removed: {result.removed_files}")
        print(f"Stub package: {result.target_root}")
        return 0

    summary = generate(
        args.output,
        sage_package=args.source,
        patterns=args.patterns or DEFAULT_PATTERNS,
        excludes=args.exclude,
        include_py=args.include_py,
        include_private=args.include_private,
        generate_all=not args.no_all_stub,
        use_runtime_docs=not args.no_runtime_docs,
        verbose=args.verbose,
        doc_language=args.doc_language,
    )
    print(f"SageMath: {summary.sage_version}")
    print(f"Discovered: {summary.discovered}")
    print(f"Generated: {summary.generated}")
    print(f"Failed: {summary.failed}")
    print(f"Output: {summary.output_root}")
    print(f"Report: {Path(summary.output_root) / 'generation-report.json'}")
    if args.strict_factories and summary.factory_unresolved:
        print(
            "Strict factory audit failed: "
            + ", ".join(summary.factory_unresolved),
            file=sys.stderr,
        )
        return 2
    if (args.strict or args.install) and (
        summary.failed or summary.factory_unresolved or summary.dynamic_unresolved
    ):
        details: list[str] = []
        if summary.failed:
            details.append(f"failed modules={summary.failed}")
        if summary.factory_unresolved:
            details.append("factories=" + ", ".join(summary.factory_unresolved))
        if summary.dynamic_unresolved:
            details.append("sage.all Any=" + ", ".join(summary.dynamic_unresolved))
        print("Strict audit failed: " + "; ".join(details), file=sys.stderr)
        return 2
    if args.install:
        if summary.failed:
            print(
                f"Refusing to install because {summary.failed} module(s) failed",
                file=sys.stderr,
            )
            return 2
        try:
            result = install_stub_package(
                Path(summary.output_root),
                Path(summary.sage_package),
                summary.sage_version,
                overwrite_unowned=args.overwrite_unowned,
                force=args.force,
            )
        except RuntimeError as exc:
            print(f"Refusing to install: {exc}", file=sys.stderr)
            return 2
        print(f"Installed: {result.installed_files}")
        if hasattr(result, "preserved_existing_files"):
            print(f"Preserved existing stubs: {result.preserved_existing_files}")
        if hasattr(result, "taken_over_files"):
            print(f"Taken over pre-existing stubs: {result.taken_over_files}")
        print(f"Stub target: {result.target_root}")
        print(f"Manifest: {result.manifest}")
    return 1 if summary.failed == summary.discovered and summary.discovered else 0
