from __future__ import annotations

import ast
import importlib.metadata
import json
import re
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


MANIFEST_NAME = ".sage-pycharm-stubgen-in-place.json"
CURATED_DOCS_NAME = ".sage-pycharm-stubgen-curated-docs.json"


def _current_version() -> str:
    try:
        return importlib.metadata.version("sage-pycharm-stubgen")
    except importlib.metadata.PackageNotFoundError:
        from . import __version__

        return __version__


def _version_tuple(version: str) -> tuple[int, ...]:
    """Numeric version key; non-numeric parts (``dev``, ``rc``) are ignored."""
    return tuple(int(part) for part in re.findall(r"\d+", version))


@dataclass(frozen=True)
class InstallationResult:
    target_root: Path
    installed_files: int
    removed_stale_files: int
    preserved_existing_files: int
    taken_over_files: int
    manifest: Path


@dataclass(frozen=True)
class UninstallResult:
    target_root: Path
    removed_files: int
    restored_backups: int


def _read_manifest(
    target: Path, manifest_name: str = MANIFEST_NAME
) -> dict[str, object]:
    manifest = target / manifest_name
    if not manifest.is_file():
        return {}
    payload = json.loads(manifest.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RuntimeError(f"Invalid manifest payload: {manifest}")
    return payload


def _manifest_files(
    target: Path, manifest_name: str = MANIFEST_NAME
) -> list[Path]:
    manifest = target / manifest_name
    payload = _read_manifest(target, manifest_name)
    result: list[Path] = []
    for raw_path in payload.get("files", []):
        relative = Path(raw_path)
        if relative.is_absolute() or ".." in relative.parts:
            raise RuntimeError(f"Unsafe path in {manifest}: {raw_path!r}")
        result.append(relative)
    return result


def _validated_generated_files(output_root: Path) -> tuple[Path, list[Path]]:
    source = output_root.resolve() / "sage"
    if not source.is_dir():
        raise RuntimeError(f"Generated sage stub directory does not exist: {source}")

    generated_files = sorted(path for path in source.rglob("*.pyi") if path.is_file())
    if not generated_files:
        raise RuntimeError(f"No .pyi files found under: {source}")

    for generated_file in generated_files:
        try:
            ast.parse(
                generated_file.read_text(encoding="utf-8"),
                filename=str(generated_file),
            )
        except (OSError, SyntaxError, UnicodeError) as exc:
            raise RuntimeError(
                f"Refusing to install invalid stub: {generated_file}: {exc}"
            ) from exc
    return source, generated_files


def _validated_sage_package(sage_package: Path) -> Path:
    target = sage_package.resolve()
    if target.name != "sage" or not (target / "all.py").is_file():
        raise RuntimeError(f"Expected an installed Sage package directory, got: {target}")
    return target


def _remove_empty_parents(path: Path, stop: Path) -> None:
    current = path.parent
    while current != stop and stop in current.parents:
        try:
            current.rmdir()
        except OSError:
            return
        current = current.parent


def install_stub_package(
    output_root: Path,
    sage_package: Path,
    sage_version: str,
    overwrite_unowned: bool = False,
    force: bool = False,
) -> InstallationResult:
    """Install generated stubs next to Sage's runtime modules.

    PyCharm's WSL interpreter indexing reliably sees ``sage/foo.pyi`` beside
    ``sage/foo.py`` or ``sage/foo.so``.  A manifest prevents the installer from
    overwriting or later removing files it does not own; with
    ``overwrite_unowned=True`` a pre-existing unowned ``.pyi`` on the same
    path is taken over, after being backed up to ``<name>.pyi.sps-bak`` so an
    uninstall can restore it.

    The manifest records the generator version.  Installing with an OLDER
    tool version than the one that produced the current stubs is refused
    (unless ``force`` is set): the newer tool's documentation enrichment
    (curated Chinese docs, return annotations) would be silently lost
    otherwise.
    """
    source, generated_files = _validated_generated_files(output_root)
    target = _validated_sage_package(sage_package)
    manifest = target / MANIFEST_NAME
    previously_owned = set(_manifest_files(target))
    existing = _read_manifest(target)
    installed_version = str(existing.get("generator_version") or "0")
    if (
        not force
        and _version_tuple(_current_version()) < _version_tuple(installed_version)
    ):
        raise RuntimeError(
            "The installed stubs were generated by a newer version "
            f"({installed_version}) of sage-pycharm-stubgen than this one "
            f"({_current_version()}).  Overwriting them would lose the newer "
            "tool's documentation enrichment (curated Chinese docs and return "
            "annotations).  Upgrade the tool (pip install -U "
            "sage-pycharm-stubgen) or pass --force."
        )

    pending: list[tuple[Path, Path]] = []
    preserved_existing = 0
    taken_over = 0
    backups: dict[str, str] = {}
    for source_file in generated_files:
        relative = source_file.relative_to(source)
        destination = target / relative
        if destination.exists() and relative not in previously_owned:
            if not overwrite_unowned:
                preserved_existing += 1
                continue
            backup = destination.with_name(destination.name + ".sps-bak")
            shutil.copy2(destination, backup)
            backups[relative.as_posix()] = backup.name
            taken_over += 1
        pending.append((source_file, relative))

    installed: set[Path] = set()
    for source_file, relative in pending:
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_file, destination)
        installed.add(relative)

    marker_relative = Path("py.typed")
    marker = target / marker_relative
    if not marker.exists() or marker_relative in previously_owned:
        marker.write_text("", encoding="utf-8")
        installed.add(marker_relative)

    # Ship the curated Chinese docs next to the installed stubs so the
    # documentation data survives in the environment even if the stubs are
    # regenerated by other tooling (audit and recovery artifact).
    curated_relative = Path(CURATED_DOCS_NAME)
    try:
        from .supplemental_docs import SUPPLEMENTAL_DOCS

        curated_payload = json.dumps(SUPPLEMENTAL_DOCS, ensure_ascii=False, indent=2)
        (target / curated_relative).write_text(
            curated_payload + "\n", encoding="utf-8"
        )
        installed.add(curated_relative)
    except Exception:  # pragma: no cover - the data module is always shipped
        pass

    stale = previously_owned - installed
    removed_stale = 0
    for relative in sorted(stale, key=lambda item: len(item.parts), reverse=True):
        stale_file = target / relative
        if stale_file.is_file():
            stale_file.unlink()
            removed_stale += 1
            _remove_empty_parents(stale_file, target)

    payload = {
        "format": 1,
        "generator": "sage-pycharm-stubgen",
        "generator_version": _current_version(),
        "sage_version": sage_version,
        "sage_package": str(target),
        "generated_from": str(output_root.resolve()),
        "installed_at": datetime.now(timezone.utc).isoformat(),
        "files": sorted(path.as_posix() for path in installed),
        "backups": backups,
    }
    manifest.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return InstallationResult(
        target,
        len(installed),
        removed_stale,
        preserved_existing,
        taken_over,
        manifest,
    )


def uninstall_stub_package(sage_package: Path) -> UninstallResult:
    target = _validated_sage_package(sage_package)
    manifest = target / MANIFEST_NAME
    if not manifest.is_file():
        return UninstallResult(target, 0)

    removed = 0
    for relative in sorted(
        _manifest_files(target),
        key=lambda item: len(item.parts),
        reverse=True,
    ):
        owned_file = target / relative
        if owned_file.is_file():
            owned_file.unlink()
            removed += 1
            _remove_empty_parents(owned_file, target)
    restored = 0
    payload = _read_manifest(target)
    backups = payload.get("backups", {})
    if isinstance(backups, dict):
        for relative, backup_name in backups.items():
            if not isinstance(relative, str) or not isinstance(backup_name, str):
                continue
            owned_file = target / Path(relative)
            backup = owned_file.with_name(backup_name)
            if backup.is_file() and not owned_file.exists():
                shutil.move(str(backup), str(owned_file))
                restored += 1
    manifest.unlink()
    return UninstallResult(target, removed, restored)
